import { useEffect,useState } from "react";
import { ArrowUpRight, Bot, CalendarCheck, CheckCircle2, MessageSquareText, Settings2, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { api,session } from "../api";
import type { Booking,OnboardingSummary } from "../types";
export default function Dashboard(){const id=session.businessId()!;const [summary,setSummary]=useState<OnboardingSummary|null>(null);const [bookings,setBookings]=useState<Booking[]>([]);useEffect(()=>{Promise.all([api.summary(id),api.bookings(id)]).then(([s,b])=>{setSummary(s);setBookings(b.slice(0,5))}).catch(()=>{})},[id]);return <div className="dashboard"><div className="page-top"><div><span className="eyebrow">Overview</span><h1>Good morning 👋</h1><p className="muted">Here’s what’s happening with your AI receptionist.</p></div><Link className="primary-button compact" to="/setup"><Settings2 size={16}/>Business setup</Link></div>
 <div className="hero-banner"><div><span className="eyebrow light-eyebrow"><Sparkles size={14}/>AI receptionist</span><h2>{summary?.readyForReceptionist?"Your receptionist is live-ready.":"Finish setup to bring your receptionist online."}</h2><p>{summary?.readyForReceptionist?"Your configured knowledge and workflows are ready for customer conversations.":"Complete the remaining setup steps and connect a customer channel."}</p></div><div className="hero-orb"><Bot size={42}/></div></div>
 <div className="metric-grid"><Metric icon={<CalendarCheck/>} label="Bookings" value={String(bookings.length)} detail="Recent bookings"/><Metric icon={<MessageSquareText/>} label="AI conversations" value="—" detail="Analytics coming next"/><Metric icon={<CheckCircle2/>} label="Setup" value={summary?.readyForReceptionist?"100%":"In progress"} detail={summary?.missingRequirements?.[0]??"All essentials configured"}/></div>
 <div className="content-grid"><section className="panel"><div className="panel-title"><div><h3>Recent bookings</h3><p>Latest customer reservations</p></div><Link to="/bookings">View all <ArrowUpRight size={15}/></Link></div>{bookings.length===0?<div className="table-empty"><CalendarCheck size={22}/><span>No bookings yet</span><small>Completed customer reservations will appear here.</small></div>:<div className="booking-list">{bookings.map(b=><div className="booking-row" key={b.bookingId}><div className="avatar">{b.customerName?.slice(0,1)||"?"}</div><div><b>{b.customerName}</b><small>{b.service}</small></div><span className={`status ${b.status.toLowerCase()}`}>{b.status}</span><b className="date">{b.bookingDate??"—"}</b></div>)}</div>}</section>
 <section className="panel"><div className="panel-title"><div><h3>Setup health</h3><p>Workspace readiness</p></div></div><div className="health-list">{[["Business information",summary?.businessInformationComplete],["Services",summary?.servicesConfigured],["Knowledge",summary?.knowledgeConfigured],["Channel",summary?.channelConfigured]].map(([label,ok])=><div key={String(label)}><span className={ok?"health-ok":"health-pending"}>{ok?<CheckCircle2 size={17}/>:<span/>}</span><span>{String(label)}</span><b>{ok?"Complete":"Pending"}</b></div>)}</div></section></div></div>}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}