import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Hotel, Hospital, MessageCircle, PartyPopper, Utensils, WandSparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { api, session } from "../api";
import type { BusinessKnowledge, Catalog, OnboardingSummary, ServiceDefinition } from "../types";

const emptyKnowledge:BusinessKnowledge={businessDescription:"",services:[],products:[],facts:{},faqs:[],policies:[],instructions:"",operatingHours:{},locations:[],contactInformation:{},bookingRules:{},capabilities:[],restrictions:[]};
const icons:Record<string,typeof Hotel>={HOSPITALITY:Hotel,RESTAURANT:Utensils,HEALTHCARE:Hospital,WOTHER:Hospital};
export default function Onboarding(){
 const nav=useNavigate(); const id=session.businessId(); const [step,setStep]=useState(0); const [catalog,setCatalog]=useState<Catalog|null>(null); const [summary,setSummary]=useState<OnboardingSummary|null>(null); const [name,setName]=useState(""); const [type,setType]=useState(""); const [description,setDescription]=useState(""); const [services,setServices]=useState<ServiceDefinition[]>([]); const [knowledge,setKnowledge]=useState<BusinessKnowledge>(emptyKnowledge); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!id){return} Promise.all([api.catalog(id),api.summary(id)]).then(([c,s])=>{setCatalog(c);setSummary(s)}).catch(e=>setError(e.message));},[id]);
 const steps=["Business","Services","Knowledge","Connect","Launch"];
 const selected=useMemo(()=>new Set(services.map(s=>s.requestType)),[services]);
 if(!id) return <CreateBusiness onCreated={(businessId)=>{session.setBusinessId(businessId);window.location.reload()}}/>;
 async function saveAndNext(){
  setBusy(true);setError("");
  try{
   if(step===0){const s=await api.saveBusiness(id,{businessName:name,businessType:type,description});setSummary(s);setStep(1)}
   else if(step===1){const s=await api.saveServices(id,services);setSummary(s);setStep(2)}
   else if(step===2){const s=await api.saveKnowledge(id,{...knowledge,businessDescription:description});setSummary(s);setStep(3)}
   else if(step===3){setStep(4)}
   else {await api.complete(id);nav("/");}
  }catch(e){setError(e instanceof Error?e.message:"Unable to save")}finally{setBusy(false)}
 }
 return <div className="onboarding-page"><div className="page-top"><div><span className="eyebrow">Setup your receptionist</span><h1>Build your business workspace</h1><p className="muted">A few details now. Your AI uses them as its operating context.</p></div><div className="progress-count">{step+1}<span>/ {steps.length}</span></div></div>
 <div className="wizard"><div className="stepper">{steps.map((s,i)=><div className={`step ${i===step?"active":""} ${i<step?"done":""}`} key={s}><span>{i<step?<Check size={14}/>:i+1}</span>{s}</div>)}</div>
 <div className="wizard-card">
 {step===0&&<><div className="section-heading"><WandSparkles/><div><h2>Tell us about your business</h2><p>We'll tailor your receptionist to your industry.</p></div></div><div className="type-grid">{(catalog?.businessTypes??[]).map(t=>{const Icon=icons[t.code]??WandSparkles;return <button className={`type-card ${type===t.code?"selected":""}`} key={t.code} onClick={()=>setType(t.code)}><Icon/><b>{t.name}</b><small>{t.description}</small>{type===t.code&&<CheckCircle2 className="selected-check" size={19}/>}</button>})}</div><div className="field-grid"><label><span>Business name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Ocean Pearl Hotel"/></label><label><span>Short description</span><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="A few words about what you offer"/></label></div></>}
 {step===1&&<><div className="section-heading"><WandSparkles/><div><h2>Choose what your AI can handle</h2><p>Start with the workflows you want customers to complete.</p></div></div><div className="service-grid">{(catalog?.suggestedServices??[]).map(s=>{const on=selected.has(s.code);return <button className={`service-card ${on?"selected":""}`} key={s.code} onClick={()=>setServices(v=>on?v.filter(x=>x.requestType!==s.code):[...v,s.definition])}><div className="service-icon"><Check size={16}/></div><div><b>{s.name}</b><small>{s.description}</small><span>{s.definition.requiredSlots.length} details collected</span></div></button>})}</div></>}
 {step===2&&<><div className="section-heading"><WandSparkles/><div><h2>Teach Inquiro your business</h2><p>Give the AI authoritative information it can safely use.</p></div></div><label className="wide-field"><span>Business knowledge</span><textarea rows={8} value={knowledge.instructions} onChange={e=>setKnowledge({...knowledge,instructions:e.target.value})} placeholder="Opening hours, policies, what makes you different, important rules, how customers should be helped…"/></label><div className="knowledge-grid"><label><span>Locations</span><input value={knowledge.locations[0]??""} onChange={e=>setKnowledge({...knowledge,locations:e.target.value?[e.target.value]:[]})} placeholder="e.g. Galle Road, Matara"/></label><label><span>Phone</span><input value={knowledge.contactInformation.phone??""} onChange={e=>setKnowledge({...knowledge,contactInformation:{...knowledge.contactInformation,phone:e.target.value}})} placeholder="+94 …"/></label></div><div className="tip"><Sparkles size={17}/><span>Be specific. The AI should only answer from information you provide or from configured workflows.</span></div></>}
 {step===3&&<ChannelStep summary={summary}/>}
 {step===4&&<LaunchStep summary={summary}/>}
 {error&&<div className="error-box">{error}</div>}
 <div className="wizard-actions">{step>0?<button className="secondary-button" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>Back</button>:<span/>}<button className="primary-button" disabled={busy||(step===0&&(!name||!type))||(step===1&&services.length===0)}>{busy?"Saving…":step===4?"Go to dashboard":"Continue"}<ArrowRight size={17}/></button></div>
 </div></div></div>
}
function CreateBusiness({onCreated}:{onCreated:(id:string)=>void}){const [name,setName]=useState("");const [type,setType]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function create(){setBusy(true);try{const r=await api.createBusiness(name,type,"");onCreated(r.businessId)}catch(e){setError(e instanceof Error?e.message:"Unable to create business")}finally{setBusy(false)}}return <div className="empty-state"><div className="empty-icon"><WandSparkles/></div><h1>Create your business</h1><p>Let's create the workspace your AI receptionist will operate in.</p><div className="field-stack"><label><span>Business name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ocean Pearl Hotel"/></label><label><span>Business type</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">Choose…</option><option value="HOSPITALITY">Hotel / Accommodation</option><option value="RESTAURANT">Restaurant</option><option value="HEALTHCARE">Clinic / Healthcare</option></select></label>{error&&<div className="error-box">{error}</div>}<button className="primary-button" disabled={!name||!type||busy} onClick={create}>{busy?"Creating…":"Create workspace"}<ArrowRight size={17}/></button></div></div>}
function ChannelStep({summary}:{summary:OnboardingSummary|null}){return <div className="connect-panel"><div className="channel-logo"><MessageCircle/></div><h2>Connect a customer channel</h2><p>Messenger and WhatsApp credentials stay encrypted in the backend. Connect the channel from Business setup after the core workspace is ready.</p><div className="channel-status"><span className={summary?.channelConfigured?"ok-dot":"pending-dot"}/><div><b>{summary?.channelConfigured?"Channel connected":"No channel connected yet"}</b><small>{summary?.channelConfigured?"Your receptionist can receive customer messages.":"You can finish setup and connect a channel from the dashboard."}</small></div></div></div>}
function LaunchStep({summary}:{summary:OnboardingSummary|null}){return <div className="launch-panel"><div className="launch-icon"><PartyPopper/></div><h2>Your receptionist is configured</h2><p>Review the essentials below. You can keep refining the workspace after launch.</p><div className="check-list">{[["Business information",summary?.businessInformationComplete],["Services",summary?.servicesConfigured],["Knowledge",summary?.knowledgeConfigured],["Channel",summary?.channelConfigured]].map(([label,ok])=><div key={String(label)}><span className={ok?"check-circle":"pending-circle"}>{ok&&<Check size={13}/>}</span><span>{String(label)}</span><b>{ok?"Ready":"Next"}</b></div>)}</div></div>}