-- Inquiro Phase 39 baseline schema for PostgreSQL.
-- JSON payloads intentionally use TEXT because the application owns their JSON shape
-- and the existing H2 schema stores them as CLOB/TEXT. JSONB can be introduced later
-- only with an explicit data/query migration.

CREATE TABLE IF NOT EXISTS business_account (
    business_id VARCHAR(128) PRIMARY KEY,
    business_name VARCHAR(255) NOT NULL,
    business_type VARCHAR(255),
    description TEXT,
    profile_json TEXT
);

CREATE TABLE IF NOT EXISTS business_channel (
    channel_id VARCHAR(128) PRIMARY KEY,
    business_id VARCHAR(128) NOT NULL,
    type VARCHAR(50) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT fk_business_channel_business
        FOREIGN KEY (business_id) REFERENCES business_account (business_id),
    CONSTRAINT uq_business_channel_type_external
        UNIQUE (type, external_id)
);

CREATE INDEX IF NOT EXISTS idx_business_channel_business
    ON business_channel (business_id);

CREATE TABLE IF NOT EXISTS conversation_session (
    session_id VARCHAR(512) PRIMARY KEY,
    business_id VARCHAR(128),
    channel_type VARCHAR(50),
    external_channel_id VARCHAR(255),
    customer_id VARCHAR(255),
    inquiry_json TEXT,
    missing_fields_json TEXT,
    last_updated TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_conversation_business_customer
    ON conversation_session (business_id, customer_id);

CREATE INDEX IF NOT EXISTS idx_conversation_last_updated
    ON conversation_session (last_updated);

CREATE TABLE IF NOT EXISTS business_request (
    request_id VARCHAR(128) PRIMARY KEY,
    business_id VARCHAR(128) NOT NULL,
    customer_id VARCHAR(255),
    service VARCHAR(255),
    fields_json TEXT,
    availability_status VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_business_request_business
        FOREIGN KEY (business_id) REFERENCES business_account (business_id)
);

CREATE INDEX IF NOT EXISTS idx_business_request_business_created
    ON business_request (business_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_business_request_business_status
    ON business_request (business_id, status);

CREATE TABLE IF NOT EXISTS user_account (
    user_id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_session (
    session_id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    CONSTRAINT fk_auth_session_user
        FOREIGN KEY (user_id) REFERENCES user_account (user_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user
    ON auth_session (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_session_expiry
    ON auth_session (expires_at);

CREATE TABLE IF NOT EXISTS business_membership (
    membership_id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    business_id VARCHAR(128) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_membership_user
        FOREIGN KEY (user_id) REFERENCES user_account (user_id),
    CONSTRAINT fk_membership_business
        FOREIGN KEY (business_id) REFERENCES business_account (business_id),
    CONSTRAINT uq_business_membership_user_business
        UNIQUE (user_id, business_id)
);

CREATE INDEX IF NOT EXISTS idx_membership_business
    ON business_membership (business_id);

CREATE TABLE IF NOT EXISTS messenger_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(64) NOT NULL UNIQUE,
    business_id VARCHAR(128) NOT NULL,
    page_id VARCHAR(255) NOT NULL,
    sender_id VARCHAR(255) NOT NULL,
    message_id VARCHAR(512),
    event_timestamp BIGINT NOT NULL,
    message_text VARCHAR(10000) NOT NULL,
    reply VARCHAR(10000),
    status VARCHAR(50) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    send_attempts INTEGER NOT NULL,
    failure_code VARCHAR(255),
    CONSTRAINT fk_messenger_inbox_business
        FOREIGN KEY (business_id) REFERENCES business_account (business_id)
);

CREATE INDEX IF NOT EXISTS idx_messenger_pending
    ON messenger_inbox (status, next_attempt_at, id);

CREATE INDEX IF NOT EXISTS idx_messenger_business_status
    ON messenger_inbox (business_id, status);
